/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import edu.princeton.cs.algs4.Draw;
import edu.princeton.cs.algs4.DrawListener;
import ifsc.poo.structure.MouseHandler;
import ifsc.poo.structure.models.Circulo;
import ifsc.poo.structure.models.Quadrado;
import ifsc.poo.structure.models.Hexagono;
import ifsc.poo.structure.models.Trapezio;
import java.awt.Color;

public class App implements DrawListener {
    private MouseHandler mouseHandler;

    public App() {
        Draw draw = new Draw();
        draw.addListener(this);
        mouseHandler = new MouseHandler(draw);
    }

    @Override
    public void mousePressed(double x, double y) {
        mouseHandler.desenharNaPosicao(x, y);
    }

    @Override
    public void keyTyped(char c) {
        if (c == 'q' || c == 'w' || c == 'p') {
            c = Character.toUpperCase(c);
        }
        mouseHandler.processarTecla((int) c);
    }

    @Override
    public void keyPressed(int keyCode) {
        mouseHandler.processarTecla(keyCode);
    }


    public static void main(String[] args) {
        new App();
    }
}