/*
 * This source file was generated by the Gradle 'init' task
 */
package ifsc.poo;

import edu.princeton.cs.algs4.Draw;
import edu.princeton.cs.algs4.DrawListener;
import ifsc.poo.structure.MouseHandler;

public class App implements DrawListener { // Implementando polimorfismo e implementando a interface DrawListener
    private final MouseHandler mouseHandler;

    public App() {
        Draw draw = new Draw();
        draw.addListener(this);
        mouseHandler = new MouseHandler(draw);
    }

    @Override
    public void mousePressed(double x, double y) { // Sobrescrevendo o método mousePressed da interface DrawListener
        mouseHandler.desenharNaPosicao(x, y);
    }

    @Override
    public void keyTyped(char c) { // Sobrescrevendo o método keyTyped da interface DrawListener
        if (c == 'q' || c == 'w' || c == 'p') {
            c = Character.toUpperCase(c);
        }
        mouseHandler.processarTecla((int) c);
    }

    @Override
    public void keyPressed(int keyCode) { // Sobrescrevendo o método keyPressed da interface DrawListener
        mouseHandler.processarTecla(keyCode);
    }


    public static void main(String[] args) {
        new App();
    }
}